/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package oop.sudoku11;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        
    }
}
